name: on_the_record
description: A new Flutter project for On the Record

# 앱 버전 및 빌드 번호
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7
  speech_to_text: ^6.4.1
  flutter_tts: ^3.8.3

  # 추가 패키지들 (필요 시 여기에 패키지 추가)
  provider: ^6.0.5
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon_calendar.svg
    - assets/icon_mic.svg
    - assets/icon_chat.svg


